from manim import *

class AugmentationLaTeX(Scene):
    def construct(self):
        omega = MathTex("\omega").shift(UP)
        init_text = MathTex("p( {{ f }} {{ | }} {{ y }} )", "=", "{ {{ \prod_{i=1}^N }} \sigma(y_i f_i) {{ p(f) }} \over {{ p(y) }} }").set_color(BLACK)
        rewrite_sigma = MathTex("p( {{ f }} {{ | }} {{ y }} )", "=", "{ {{ \prod_{i=1}^N }} { {{ e^{y_if_i \over 2 } }} \over 2\cosh({|f_i| \over 2}) } {{ p(f) }} \over {{ p(y) }} }").set_color(BLACK)
        use_integral = MathTex("p( {{ f }} {{ | }} {{ y }} )", "=", "{ {{ \prod_{i=1}^N }} {{ {1 \over 2} }} {{ e^{y_if_i \over 2 } }} \int_0^\infty {{ e^{-f_i^2\omega_i \over 2} }} {{ \mathrm{PG}(\omega_i|1, 0) }} d {{ \omega_i }} {{ p(f) }} \over {{ p(y) }} }").set_color(BLACK)
        final_text = MathTex("p( {{ f }}, \{ {{ \omega_i }} \}_{i=1}^N {{ | }} {{ y }} )", "=",  "{ {{ \prod_{i=1}^N }} {{ {1 \over 2} }} {{ e^{y_if_i \over 2} }} {{ e^{-f_i^2\omega_i \over 2} }} {{ \mathrm{PG}(\omega_i|1, 0) }} {{ p(f) }} \over {{ p(y) }}}").set_color(BLACK)
        cond_f = MathTex("p(f|y, \{\omega_i\}_{i=1}^N) \propto {{ \prod_{i=1}^N }} {{ e^{y_if_i \over 2} }} {{ e^{-f_i^2\omega_i \over 2} }} {{ p(f) }}").set_color(BLACK)
        cond_f.next_to(final_text, DOWN)

        scale = Text("Representation as a scale-mixture:").set_color(BLACK)
        definition = MathTex("\cosh^{-1}(f) = \int_0^\infty e^{-f^2\omega}\mathrm{PG}(\omega|1,0)d\omega").set_color(BLACK)
        aug = Text("Latent variable augmentation").set_color(BLACK)
        definition.next_to(init_text, UP)        
        scale.next_to(definition, UP)        
        aug.next_to(definition, UP)        
        self.add(init_text)
        # self.play(Write(init_text))
        self.wait(3)
        self.play(TransformMatchingTex(init_text, rewrite_sigma, fade_transform_mismatches=True), run_time=3)
        # self.add(rewrite_sigma)
        self.play(FadeIn(scale), FadeIn(definition), run_time=1)
        self.wait(4)        
        use_integral.next_to(rewrite_sigma, DOWN)
        self.play(TransformMatchingTex(rewrite_sigma.copy(), use_integral, transform_mismatches=True), run_time=3)
        self.play(FadeOut(scale), FadeOut(definition), FadeIn(aug), run_time=1)
        self.wait(3)
        final_text.next_to(rewrite_sigma, DOWN)
        self.play(TransformMatchingTex(use_integral, final_text, transform_mismatches=False), run_time=3)
        # self.wait()
        # self.play(TransformMatchingTex(final_text.copy(), cond_f, transform_mismatches=False), FadeOut(aug), run_time=3)
